from PySide6.QtCore import QRect, Qt
from PySide6.QtWidgets import (
    QWidget, QSpinBox, QLabel, QPushButton, QRadioButton, QSlider, QComboBox
)
from windows.drop_line import DropLineEdit

class Segmentation_Window(object):
    def __init__(self, centralwidget):
        self.seg_panel = QWidget(centralwidget)
        self.seg_panel.setObjectName("seg_panel")
        self.seg_panel.setFixedWidth(320)

        self.BF_label = QLabel("Folder", self.seg_panel)
        self.BF_label.setObjectName("BF_label")
        self.BF_label.setGeometry(QRect(20, 40, 60, 21))
        self.BF_lineEdit = DropLineEdit(self.seg_panel, "folder")
        self.BF_lineEdit.setObjectName("BF_lineEdit")
        self.BF_lineEdit.setGeometry(QRect(90, 40, 161, 21))
        self.BF_lineEdit.setClearButtonEnabled(False)
        self.BF_btn = QPushButton("^", self.seg_panel)
        self.BF_btn.setObjectName("BF_btn")
        self.BF_btn.setGeometry(QRect(253, 35, 48, 32))

        self.model_label = QLabel("Model", self.seg_panel)
        self.model_label.setObjectName(u"model_label")
        self.model_label.setGeometry(QRect(20, 90, 90, 16))
        self.model_comboBox = QComboBox(self.seg_panel)

        self.model_comboBox.addItem("MET")

        self.model_comboBox.setObjectName(u"model_comboBox")
        self.model_comboBox.setGeometry(QRect(105, 90, 120, 26))
        self.model_comboBox.setEnabled(False)

        self.label_label = QLabel("Label", self.seg_panel)
        self.label_label.setObjectName("label_label")
        self.label_label.setGeometry(QRect(20, 150, 60, 21))

        self.radioButton_1 = QRadioButton("1", self.seg_panel)
        self.radioButton_1.setObjectName("radioButton_1")
        self.radioButton_1.setGeometry(QRect(70, 150, 41, 20))
        self.radioButton_1.setEnabled(False)
        self.radioButton_1.setAutoExclusive(False)
        self.radioButton_2 = QRadioButton("2", self.seg_panel)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_2.setGeometry(QRect(110, 150, 41, 20))
        self.radioButton_2.setEnabled(False)
        self.radioButton_2.setAutoExclusive(False)
        self.radioButton_3 = QRadioButton("3", self.seg_panel)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_3.setGeometry(QRect(150, 150, 41, 20))
        self.radioButton_3.setEnabled(False)
        self.radioButton_3.setAutoExclusive(False)
        self.radioButton_4 = QRadioButton("4", self.seg_panel)
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_4.setGeometry(QRect(190, 150, 41, 20))
        self.radioButton_4.setEnabled(False)
        self.radioButton_4.setAutoExclusive(False)
        self.radioButton_5 = QRadioButton("5", self.seg_panel)
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_5.setGeometry(QRect(230, 150, 41, 20))
        self.radioButton_5.setEnabled(False)
        self.radioButton_5.setAutoExclusive(False)

        self.label_op_label = QLabel("Label Opacity", self.seg_panel)
        self.label_op_label.setObjectName("label_op_label")
        self.label_op_label.setGeometry(QRect(20, 180, 91, 21))
        self.LO_spinBox = QSpinBox(self.seg_panel)
        self.LO_spinBox.setObjectName("LO_spinBox")
        self.LO_spinBox.setGeometry(QRect(110, 180, 61, 24))
        self.LO_spinBox.setMinimum(1)
        self.LO_spinBox.setMaximum(40)
        self.LO_spinBox.setValue(20)
        self.LO_spinBox.setSingleStep(1)
        self.LO_spinBox.setEnabled(False)

        self.ot_label = QLabel("Orientation", self.seg_panel)
        self.ot_label.setObjectName(u"ot_label")
        self.ot_label.setGeometry(QRect(20, 310, 90, 16))
        self.slice_comboBox = QComboBox(self.seg_panel)
        self.slice_comboBox.addItem("axial (xy)")
        self.slice_comboBox.addItem("sagittal (yz)")
        self.slice_comboBox.addItem("coronal (xz)")
        self.slice_comboBox.setObjectName(u"slice_comboBox")
        self.slice_comboBox.setGeometry(QRect(105, 305, 120, 26))
        self.slice_comboBox.setEnabled(False)

        self.slice_horizontalSlider = QSlider(self.seg_panel)
        self.slice_horizontalSlider.setObjectName(u"slice_horizontalSlider")
        self.slice_horizontalSlider.setGeometry(QRect(20, 370, 280, 22))
        self.slice_horizontalSlider.setOrientation(Qt.Horizontal)
        self.slice_horizontalSlider.setEnabled(False)

        self.slice_label = QLabel("Slice:", self.seg_panel)
        self.slice_label.setObjectName(u"slice_label")
        self.slice_label.setGeometry(QRect(20, 340, 41, 16))
        self.slice_idx_label = QLabel(self.seg_panel)
        self.slice_idx_label.setObjectName(u"slice_idx_label")
        self.slice_idx_label.setGeometry(QRect(60, 340, 41, 16))

        self.render_pushButton = QPushButton("Render", self.seg_panel)
        self.render_pushButton.setObjectName("render_pushButton")
        self.render_pushButton.setGeometry(QRect(160, 430, 113, 32))
        self.render_pushButton.setEnabled(False)

        self.seg_pushButton = QPushButton("Run", self.seg_panel)
        self.seg_pushButton.setObjectName("seg_pushButton")
        self.seg_pushButton.setGeometry(QRect(30, 430, 113, 32))
        self.seg_pushButton.setEnabled(False)

        self.savePNG_pushButton = QPushButton("Save PNG", self.seg_panel)
        self.savePNG_pushButton.setObjectName("savePNG_pushButton")
        self.savePNG_pushButton.setGeometry(QRect(30, 480, 113, 32))
        self.savePNG_pushButton.setEnabled(False)

        self.saveMP4_pushButton = QPushButton("Save MP4", self.seg_panel)
        self.saveMP4_pushButton.setObjectName("saveMP4_pushButton")
        self.saveMP4_pushButton.setGeometry(QRect(160, 480, 113, 32))
        self.saveMP4_pushButton.setEnabled(False)